print("Test window")
print("Test window")
print("Test window")
print("Test window")
print("Test window")
print("Test window")
print("Test window")
print("Test window")
mirror = "astonish"
print(mirror)